# robotic_arm_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #Position Controllers --------------------------------------
  robotic_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - Rev11
      - Rev12
      - Rev13
      - Rev14
      - Rev15
      - Rev16
      - Rev17
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      Rev11: {trajectory: 0.1, goal: 0.1}
      Rev12: {trajectory: 0.1, goal: 0.1}
      Rev13: {trajectory: 0.1, goal: 0.1}
      Rev14: {trajectory: 0.1, goal: 0.1}
      Rev15: {trajectory: 0.1, goal: 0.1}
      Rev16: {trajectory: 0.1, goal: 0.1}
      Rev17: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

  joint_group_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - Rev11
      - Rev12
      - Rev13
      - Rev14
      - Rev15
      - Rev16
      - Rev17