controller_list:
  - name: "robotic_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Rev11
      - Rev12
      - Rev13
      - Rev14
      - Rev15
      - Rev16
      - Rev17
