controller_list:
  - name: fake_robotic_arm_controller
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
      - Rev6
      - Rev7
  - name: fake_gripper_controller
    joints:
      - Rev8